export default {
  tabIconDefault: 'grey',
  tabIconSelected: 'black',
  boxShadowColor: '#d6d6d6',
  blueColor: '#0072bc',
  darkBlueColor: '#005f9d',
  lightBlueColor: '#64c1ff',
  transparentBlueColor: 'rgba(0,0,0,0)',
  greyColor: '#e8e9ea',
  darkGreyColor: '#82878c',
  lightGreyColor: '#e5e5e5',
  blackColor: '#000000',
  backgroundColor: '#ffffff',
  successColor: '#5cb85c',
  warningColor: '#f0ad4e',
  dangerColor: '#d9534f',
  infoColor: '#5bc0de',
};
